### ISSUE TITLE
Is it expected to get [name].cshtml and [name].js.cshtml?

### ISSUE THREAD

**Issue by CGollhardt** [jouni-kantola/razor-partial-views-webpack-plugin#50]
Or is it expected to get a single [name].cshtml which includes both Javascript and Style tags (Which I expect)?
Has this something todo with webpack 5?

`new RazorPartialViewsWebpackPlugin()` gives:

```
25.02.2021  19:52                40 main.cshtml
25.02.2021  19:52           931.419 main.css
25.02.2021  19:52         7.314.220 main.js
25.02.2021  19:52                55 main.js.cshtml

```

This:

            new RazorPartialViewsWebpackPlugin({
                rules: [
                    {
                        test: /main\.(css|js)$/,
                        output: {
                            name: 'wtf'
                        }
                    }
                ]
            })

Gives:

>ERROR in Conflict: Multiple assets emit different content to the same filename wtf.cshtml

**Comment by jouni-kantola** [comment]
Thanks for reaching out. 

A couple of things related to this:
1. Currently only one asset per view is supported 
2. The rule you're creating would get the same name for both partials (see: https://github.com/jouni-kantola/templated-assets-webpack-plugin/issues/67)

I recommend you do this instead: 
```javascript 
{
    test: /\.css$/,
    output: {
      name: defaultName => `${defaultName.split(".")[0]}-styles`,
    }
},
```

**Comment by CGollhardt** [comment]
Thanks for the fast response. This explains it. I thought it would be more for a whole entry point and thought that wp5 is tricking me.

Just following your great guide here for hmr, while migrating from 4 to 5 the same time 🙈
https://jouni.kantola.se/blog/2020-03-10/webpack-assets-in-aspnet/

Thanks for your time and effort :)

**Comment by jouni-kantola** [comment]
I'm glad you like the blog 😁 Good luck!
