### ISSUE TITLE
TypeError: Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by Chris3y** [jouni-kantola/razor-partial-views-webpack-plugin#70]
｢wdm｣: TypeError: Cannot read property 'tapAsync' of undefined
    at compiler.hooks.emit.tap (<anonPath>\node_modules\webpack-dev-middleware\lib\fs.js:22:37)
    at _next0 (eval at create (<anonPath>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at _err0 (eval at create (<anonPath>\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at TemplatedAssets.process.then.templatedAssets (<anonPath>\node_modules\templated-assets-webpack-plugin\lib\tap.js:41:7)

**Comment by Chris3y** [comment]
Got this error as soon as I added plugin

**Comment by jouni-kantola** [comment]
@Chris3y Thanks for reaching out. Make sure you've configured the plugin in the `plugins` section of webpack's config. If that doesn't help, please provide a sample repro with `package.json` and `webpack.config.js`.

**Comment by Chris3y** [comment]
Thanks. I will dump the package and config if necessary (need to anonymize) some stuff first.

Essentially I followed your article at https://jouni.kantola.se/blog/2020-03-10/webpack-assets-in-aspnet/ to the letter. 

With some more troubleshooting, I discovered that "writeToDisk: true," causes the above error. If I remove that, if goes away but the comment indicates it's required for ASP.net

**Comment by jouni-kantola** [comment]
The versions you're using may come into play. With webpack 5, I no longer use `writeToDisk: true`.

For reference, with webpack 5 and ASP.NET Core, I use the following configuration for `devServer` and `razor-partial-views-webpack-plugin`:
```javascript
devServer: {
  compress: true,
  port: 9000,
  headers: {
      "Access-Control-Allow-Origin": "*",
  },
  server: {
      type: "https",
      options: {
          key: fs.readFileSync(path.join(__dirname, "localhost-key.pem")),
          cert: fs.readFileSync(path.join(__dirname, "localhost.pem")),
      },
  },
}
```

```javascript
plugins: [
    new RazorPartialViewsWebpackPlugin({
        rules: [
            {
                test: /(app|vendor).*\.js$/,
                exclude: /hot-update/,
                output: {
                    path: path.join(__dirname, "wwwroot/dist"),
                    emit: false,
                    name: (defaultName) => `${defaultName.split(".")[0]}`,
                },
            },
            // other asset rules ...
        ],
    }),
    // other plugin configurations ...
],
```

Please let me know if that helps.

**Comment by jouni-kantola** [comment]
Did you get it working, @Chris3y?

**Comment by jouni-kantola** [comment]
Closing inactive issue.
